### ISSUE TITLE
Pass payload/arguments through to thunk?

### ISSUE THREAD

**Issue by mockdeep** [reduxjs/redux-thunk#143]
One thing I'm finding myself wishing for is a way to get the arguments passed from the action creator to the thunk without having to create the function on the fly, e.g.:

```js
function createTaskThunk(dispatch, getState, taskAttrs) {
  dispatch...
  fetch...
    success => dispatch...
}

function createTask() {
  return createTaskThunk;
}
```

Partly just a stylistic preference, but this also avoids having to instantiate a new function  on every call vs:

```js
function createTask(taskAttrs) {
  return (dispatch, getState) => {
    dispatch...
    fetch...
      success => dispatch...
  };
}
```

I also like to be able to write tests against what gets dispatched, so if we can have a constant function, we can write tests like:

```js
expect(dispatch).toHaveBeenCalledWith(createTask());
```

Is there a way that something like this can be accomplished with `redux-thunk`?

**Comment by nullberri** [comment]
You can do it, but you need to create a new bindActionCreators from redux

```
function bindActionCreator(actionCreator, dispatch) {
  return (...args) => {
        dispatch((dispatch,state)=>{
             actionCreator(dispatch,state,...args) 
        })
    }
}
```
then you can write your action thunks like so

```
function createTaskThunk(dispatch, getState, taskAttrs) {
  dispatch...
  fetch...
    success => dispatch...
}
```

full replacement for bind action creators is here
https://gist.github.com/nullberri/4e6672536c73573c1583725f59b0c884
