### ISSUE TITLE
 Actions must be plain objects. Use custom middleware for async actions.

### ISSUE THREAD

**Issue by sagarjpawar** [reduxjs/redux-thunk#157]
![ie issue](https://user-images.githubusercontent.com/3666279/30636123-4712aaee-9e12-11e7-9703-300b9c8d8ebc.png)

 Previously it was working properly in ie11,However I am facing this issue from last week in IE11.It works on both firefox and chrome.

store.js
`import rootReducer from '../reducers';
import thunk from 'redux-thunk';
import {applyMiddleware, compose, createStore} from 'redux';
import createLogger from 'redux-logger';
import routes from '../routes';
import createHistory from 'history/lib/createHashHistory';
import {reduxReactRouter} from 'redux-router';
import config from '../common/config';

export default function configureStore(initialState) {
    let createStoreWithMiddleware;

    const logger = createLogger();
    let history = createHistory({
        queryKey: false
    });

    let middleware = applyMiddleware(thunk, logger);
    if(config.Environment == 'PROD'){
        middleware = applyMiddleware(thunk);
    }

    createStoreWithMiddleware = compose(
        middleware,reduxReactRouter({ routes, history })
    );

    const store = createStoreWithMiddleware(createStore)(rootReducer, initialState);

    if (module.hot) {
        module.hot
            .accept('../reducers', () => {
                const nextRootReducer = require('../reducers/index');
                store.replaceReducer(nextRootReducer);
            });
    }

    return store;
}
`

package.json

`......
  "dependencies": {
    "babel": "^5.8.23",
    "babel-core": "^5.2.17",
    "babel-loader": "^5.0.0",
    "body-parser": "^1.12.4",
    "cookie-parser": "^1.3.3",
    "debug": "^2.2.0",
    "dotenv": "^1.2.0",
    "errorhandler": "^1.4.2",
    "es6-promise": "^3.0.2",
  .....
    "highcharts": "5.0.0",
    "history": "^1.9.0",
   .....
    "lodash": "^4.13.1",
    "material-ui": "0.18.2",
    "material-ui-pagination": "^1.0.1",
   ....
    "react": "15.4.1",
    "react-addons-css-transition-group": "^15.2.1",
    "react-addons-linked-state-mixin": "^15.2.1",
    ...
    "react-redux": "^4.4.5",
    "react-router": "^2.6.0",
    "react-tap-event-plugin": "2.0.1",
     "redux": "^3.5.2",
    "redux-logger": "^2.6.1",
    "redux-router": "^2.0.0",
    "redux-thunk": "^2.1.0",
    "rimraf": "^2.5.2"
  },
  "devDependencies": {
    "babel-loader": "^5.0.0",
    "file-loader": "^0.8.4",
    "redux-devtools": "^3.0.1",
    "redux-devtools-dock-monitor": "^1.0.1",
    "redux-devtools-log-monitor": "^1.0.1",
    "webpack": "^1.11.0",
    "webpack-dev-server": "^1.10.1"
  },
  ......
`

Need Help please.

**Comment by benhunt29** [comment]
I'm seeing this as well

**Comment by sagarjpawar** [comment]
I faced this issue as, i was using react-google map which was throwing error.I just upgraded the google map and removed the sensor param from google map url.(
https://maps.googleapis.com/maps/api/js?key=..&sensor=false to
https://maps.googleapis.com/maps/api/js?v=3&key=..)

**Comment by benhunt29** [comment]
@sagarjpawar Thanks for the response, it's definitely a problem with the google maps api (if don't include it, everything loads). I didn't have the `sensor` property specified and I tried adding the `v=3` param but that didn't do anything. The weirdest thing about it all is that I'm not using any additional react libraries dealing with google maps, I'm just simply calling the api directly. I'm not sure how this is getting interpreted as an error by redux. If I turn on 'compatibility view' in IE11, the page loads. Any help is appreciated!

**Comment by nachein** [comment]
@benhunt29 I have experienced a similar issue not so long ago. We fixed it by specifying `v=3`, but a couple of days ago it started happening again. If I specify `v=3.29` it starts working fine again. I'm currently investigating this so if I have any other findings I'll update.

**Comment by francisco-delgado** [comment]
So we ran in to the same issue (as we weren't specifying a version) and explicitly stating `v=3.29` for the Google Maps API works. Thanks for the help here.

Has anyone found a way to send this issue to Google so they can repro easily and fix in the next version?

**Comment by dmnd** [comment]
This thread helped a lot when debugging what was going on. Thanks @nachein & others!

For us, this actually had nothing to do with `redux-thunk`. We saw this issue via `redux` itself: `redux` calls lodash's `isPlainObject` function. 

Without google maps, `isPlainObject` seemed to work as expected. But when we included the google maps API with `v>=3.30`, `isPlainObject({})` would (crazily) return `false`!

While debugging I noticed that `{}.toString` returned `"[Object array iterator]"` which I think confused lodash.

I can only assume Google Maps is writing to `Object.prototype` somewhere, or otherwise messing with the browser environment.

**Comment by nachein** [comment]
you are totally right @dmnd, about not being related to redux-thunk but redux itself, and about `isPlainObject` issue.

After a bit of debugging I can see that the error occurs on reduxs' init action, and if I test `isPlainObject({})` I also get false.

**Comment by benhunt29** [comment]
@nachein great, I'll try that out. Thanks!

**Comment by null-reference** [comment]
I'm not sure this is the _best_ way to work around this, but for now I have added a polyfill for `Symbol `prior to loading the maps script...

`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Symbol"></script>`

**Comment by nachein** [comment]
Just a quick update here on how I was able to work around this issue since it appears that version 3.29 no longer works.

I just had to defer the loading of the gmaps script by adding `defer=true`:

```<Helmet
      script={[
        { defer: true, type: 'text/javascript', src: getGoogleMapSrc() }
      ]}
    />```

@null-reference In my case, I was already using babel polyfill.

**Comment by rishisharma08** [comment]
@nachein 
ive been chasing this issue down for months. i am not using google maps api. I think i concluded that one of the APIs on the site is trying to add some sort of polyfill resulting in  `object Array Iterator` and redux hates that since its not a pure object anymore.
