### ISSUE TITLE
`withStore` extra argument?

### ISSUE THREAD

**Issue by enapupe** [reduxjs/redux-thunk#160]
Any chance we have an additional function argument that receives the store and forwards it to the action? Something like:

```
function createThunkMiddleware(extraArgument, withStore = Function.prototype) {
  return ({ dispatch, getState }) => next => action => {
    if (typeof action === 'function') {
      return action(dispatch, getState, extraArgument, withStore(getState))
    }

    return next(action)
  }
}

const thunk = createThunkMiddleware()
thunk.withExtraArgument = createThunkMiddleware

export default thunk
```

The motivation for this function callback is that I always have to call `getState()` within my authenticated action to get the user-key from the store:

```
export const getMembers = org => (dispatch, getState) =>
  dispatch({
    type: GET_MEMBERS,
    payload: getOrgMembers(getState().auth.get('key'))(org),
    meta: { org },
  })
```

With that little hack I could have the get user-key logic into just a single place:

```
export const getMembers = org => (dispatch, getState, extraArg, key) =>
  dispatch({
    type: GET_MEMBERS,
    payload: getOrgMembers(key)(org),
    meta: { org },
  })
```

The `withStore` function would be as simple as:
```
const withStore = (getState) => getState().auth.get('key')`
applyMiddleware(
  thunk.withExtraArgument(undefined, withStore),
  [...]
)
```

I understand thunk is supposed to be as simple and lightweight as possible and maybe this is out of scope, but this doesn't seem to add much overhead (unless you do something expensive with that fn) and also doesn't break the API..
Thanks!

edit: this is more or less the actual implementation https://github.com/gaearon/redux-thunk/compare/master...enapupe:with-state?expand=1

**Comment by march08** [comment]
@enapupe i have a solution for you! Released my first lib: [https://github.com/march08/redux-thunker](https://github.com/march08/redux-thunker)

**Comment by renanpallin** [comment]
Hi! I know this is close for a while, but I've just had a similar problem and made a PR to solve. Could help in your case too.

#232
