### ISSUE TITLE
confusing statement in readme

### ISSUE THREAD

**Issue by JonET** [reduxjs/redux-thunk#163]
>If you’re not sure whether you need it, you probably don’t.

This reads like the readme is talking down to me for not immediately knowing what this library is supposed to do.  In any case, it's not very helpful.

**Comment by jezzasan** [comment]
> In any case, it's not very helpful.

just like opening this issue tbqh

**Comment by LoisotheCrow** [comment]
You know you don't really have problems when the main thing you're conserned with is snarky tone in readme.

**Comment by JonET** [comment]
Are you saying that documentation issues aren't valid?
Beyond the tone I just found the statement to be confusing. This turned out to be exactly the library I needed before I even understood what it was. I think you could improve the readme by removing it.

**Comment by Scribblerockerz** [comment]
> If you’re not sure whether you need it, you probably don’t.

This statement is helpful and misleading at the same time, but it depends on the reader.
I personally found it great, because of that you think twice if you really need this module or not.
