### ISSUE TITLE
Not compatible with react@16.0.0

### ISSUE THREAD

**Issue by jlf123** [reduxjs/redux-thunk#165]
I am working on a React-Native app and am unable to use this with React@16.0.0. I receive this UNMET PEER DEPENDENCY error when trying to install with npm.

> ~react-thunk@1.0.0 requires a peer of react@~0.14.0 || ^15.0.0 but none was installed.

When I try running my app in the iOS simulator I am presented with...
<img width="345" alt="screen shot 2017-11-08 at 4 46 43 pm" src="https://user-images.githubusercontent.com/13322508/32578859-74df9690-c4a4-11e7-96fe-9d45f10afa3a.png">

**Comment by TrySound** [comment]
@jlf123 Wrong package. This is REDUX thunk. Failed package is REACT thunk. For the same reason webpack cannot find this package.

**Comment by jlf123** [comment]
oh my mistake, thanks!
