### ISSUE TITLE
TypeScript errors when wrapping component with connect()

### ISSUE THREAD

**Issue by atrauzzi** [reduxjs/redux-thunk#167]
I'm sure this subject has been explored a fair bit already, but I haven't been able to figure out the solution for what's going on here.

https://github.com/atrauzzi/gerty/blob/update-dependencies/src/Layer/GertyReactMaterialUi/Component/Setting/WorkspaceSettings.tsx#L148-L158

The error I end up with is pretty involved and difficult to parse:

```
[ts]
Argument of type 'typeof WorkspaceSettingsComponent' is not assignable to parameter of type 'ComponentType<{ workspace: Workspace; repositories: { [relativePath: string]: Repository; }; } & ...'.
  Type 'typeof WorkspaceSettingsComponent' is not assignable to type 'StatelessComponent<{ workspace: Workspace; repositories: { [relativePath: string]: Repository; };...'.
    Type 'typeof WorkspaceSettingsComponent' provides no match for the signature '(props: { workspace: Workspace; repositories: { [relativePath: string]: Repository; }; } & { dispatch: (action: Action) => (dispatch: (action: Action) => void) => Promise<void>; saveWorkspace: () => (dispatch: (action: any) => void, getState: () => GertyState, bundle: Bundle) => Promise<void>; removeRepository: (relativePath: string) => (dispatch: (action: any) => void, getState: () => GertyState) => Promise<void>; openRepositoryFolder: (relativePath: string) => (dispatch: (action: any) => void, getState: () => GertyState, bundle: Bundle) => Promise<void>; closeWorkspace: () => (dispatch: (action: any) => void, getState: () => GertyState, bundle: Bundle) => Promise<void>; } & { children?: ReactNode; }, context?: any): ReactElement<any>'.
```

I guess what I'm hoping for is a way to get around this error without resorting to using `any` in certain places just to silence the compiler.  Advice and guidance greatly appreciated, I'm sure others are having similar issues to me on this one, so further exploration here with my project above as an example may be helpful.

**Comment by gkemp94** [comment]
@atrauzzi Did you ever figure out the way forward?

**Comment by atrauzzi** [comment]
Unfortunately, not quite.  I usually just fiddle with the types of things until it all works.  The truth is I haven't quite internalized the `connect` signature.

That, combined with the chance that the generic parameters of `connect` are either not quite right, in the wrong order or not being propagated creates a confusing situation.
