### ISSUE TITLE
Navigation not working with thunk

### ISSUE THREAD

**Issue by marcosmartinez7** [reduxjs/redux-thunk#176]
Hi, can you please check if this is related with some version of react thunk? https://github.com/aksonov/react-native-router-flux/issues/2865

im using:

"redux-thunk": "^2.2.0",
"react-redux": "^5.0.6",
"react": "16.0.0"

kind regards

**Comment by marcosmartinez7** [comment]
Close it please, the problem isnt with thunk, is with RNRF support of react-navigation.

**Comment by tracker1** [comment]
Have you considered [redux-first-router](https://www.npmjs.com/package/redux-first-router)?

**Comment by marcosmartinez7** [comment]
No, i havent. I will take a look to that library. Thanks!
