### ISSUE TITLE
createAction

### ISSUE THREAD

**Issue by tracker1** [reduxjs/redux-thunk#179]
would be nice to include a createAction method to make it easier to interact with simple async functions...

    export const createAction = 
      (beforeType, successType, errorType, fn) => (...args) => (dispatch) => {
        dispatch({ type: beforeType, payload: args })
        return Promise.resolve(fn(...args))
          .then(payload => dispatch({ type: successType, payload }))
          .catch(payload => dispatch({ type: errorType, payload }));
          
      };

That could be used as...

    import createAction from 'redux-thunk/create-action';

    export loadTodos = export loadTodos = createAction(
      'LOAD_TODO_START',   // before
      'LOAD_TODO_SUCCESS', // then payload = result
      'LOAD_TODO_ERROR',   // catch payload = error
      async (/* exposed args here */) => fetch('/todos'),
    );

    ...

        dispatch(loadTodos());

        dispatch(anotherAction(arg1, arg2));

**Comment by dgrubelic** [comment]
https://github.com/agraboso/redux-api-middleware
