### ISSUE TITLE
Multiple dispatches cause infinite loop

### ISSUE THREAD

**Issue by borisyordanov** [reduxjs/redux-thunk#184]
On my components ComponentWillMount event i dispatch the `getHomepageTours` action:

```
export const getAllHomeTours = tours => ({
	type: actionTypes.GET_ALL_HOME_TOURS,
	tours
});

export const getHomepageTours = () => async dispatch => {
	try {
		dispatch(loading(true));
              
                //get data from firebase services
		await Promise.all([getAllPublishedLightToursService(), getAllFeaturedToursService()]).then(
			values => {
				const tours = values[0];
				const featuredTours = values[1];

				const homeTours = {
					cultural: [],
					history: [],
					adventure: []
				};
                                // filter and sort the data
				Object.values(featuredTours).forEach(tour => {
					if (tours.hasOwnProperty(tour.id)) {
						const fullTour = tours[tour.id];
						fullTour.id = tour.id;
						homeTours[tour.category].push(fullTour); // add the tour to the corresponding category
					}
				});
                
                                // update store
                                dispatch(getAllHomeTours(homeTours));
                
				dispatch(loading(false));// this causes the infinite loop
			}
		);
	} catch (e) {
		dispatch(loading(false));
	}
};
```

If i dispatch the `loading(false)` action the app runs into an infitie loop where this action gets called because the component i'm working on keeps remounting due to the HOC that handles loading. 

```
const withLoading = Component => {
	class WithLoading extends React.Component {
		render() {
			console.log(this.props.loading);

			if (this.props.loading) {
				return <Loading />;
			}
			return <Component {...this.props} />;
		}
	}

	const mapStateToProps = state => ({
		loading: state.loading.isLoading
	});

	return connect(mapStateToProps)(WithLoading);
};
```

If i don't do the `loading(false)` the data is loaded once and everything work well, but of course the app is stuck at a loading screen. 

Another situation when the infinite loop happens is with this action:
```
export const getCartData = () => async (dispatch, getState) => {
	try {
		dispatch(loading(true));
		const cart = Object.assign({}, getState().cart);

		const promises = Object.values(cart).map(async cartItem => {
			cart[cartItem.tourId].tour = await getTourOnceById(cartItem.tourId);
		});

		await Promise.all(promises);

		dispatch(updateCart(cart));

		dispatch(loading(false));
	} catch (err) {
		console.error(err);
		dispatch(loading(false));
	}
};
```
In this synchronous action though everyting works well.
```
export const updateCartDates = (itemId, date) => (dispatch, getState) => {
	dispatch(loading(true));

	const cart = Object.assign({}, getState().cart);

	cart[itemId].date = date;

	dispatch(updateCart(cart));
	dispatch(loading(false));
};
```

The firebase services i'm using pretty much all look something like this:
```
export const getTourOnceById = id =>
	firebase
		.database()
		.ref(toursEndpoint)
		.child(id)
		.once('value')
		.then(async snapshot => {
			const tour = snapshot.val();
			if (tour && tour.relatedTours) {
				const promises = Object.keys(tour.relatedTours).map(async id => {
					tour.relatedTours[id] = await getLightTourDetails(id);
				});
				await Promise.all(promises);
			}
			return tour;
		});
```

Last but not least, something that completely baffled me:
```
export const setTour = tour => ({
  type: actionTypes.SET_TOUR,
  tour
});

export const getTourDetails = id => async dispatch => {
  try {
    dispatch(loading(true));

    const tour = await getTourDetailsService(id);

    // this dispatch doesn't work (causes an infinite loop)
    // dispatch(setTour(tour));

    // this works however ?!
    dispatch({
      type: actionTypes.SET_TOUR,
      tour
    });

    dispatch(loading(false));
  } catch (err) {
    console.error(err);
    dispatch(loading(false));
  }
};

```
Can anyone tell me what i'm doing wrong?

**Comment by MGKhKhD** [comment]
About the last baffling issue, I also do know exactly what is going on. But, I do not know either if you code is actually meant to be equivalent to what I understand from it: 

`export const getTourDetails = id => dispatch => {
dispatch(loading(true));
return api.getTourDetailsService(id). then(res =>dispatch(setTour(tour))).then(_=>dispatch(loading(false)))   
};`

Also, in the classic example RedditApp in the official documentation, they mention to not use catch and instead use something like the following snippet. Though the problem is different in your case, I guess this may help you dealing with infinite loop.
`return fetch(`https://www.reddit.com/r/${subreddit}.json`)
      .then(
        response => response.json(),
        // Do not use catch, because that will also catch
        // any errors in the dispatch and resulting render,
        // causing a loop of 'Unexpected batch number' errors.
        // https://github.com/facebook/react/issues/6895
        error => console.log('An error occurred.', error)
      )
      .then(json =>
        // We can dispatch many times!
        // Here, we update the app state with the results of the API call.
 
        dispatch(receivePosts(subreddit, json))
      )`
