### ISSUE TITLE
2.3.0 - Import issues for interop default require

### ISSUE THREAD

**Issue by eastwood** [reduxjs/redux-thunk#199]
Hi,

I stumbled across an issue in my code base when a rebuild went out with `2.3.0`.  The issue seems to be related to the specification of es6 module interoperability whereby for consumers using:

```
import thunk from 'redux-thunk'

console.log(thunk) // returns some object { default: f()} 
```

Digging deeper into the compiled code, I've debugged that:
```
var _reduxThunk = __webpack_require__(71);
var _reduxThunk2 = _interopRequireDefault(_reduxThunk);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var store = (0, _redux.createStore)(_rootReducer2.default, (0, _redux.applyMiddleware)(_reduxThunk2.default));
```

The check for `__esModule` fails and it wraps the object in another `default`.
This is problematic, as ES6 imports do not seem to be consuming the `default` export correctly.

I'm currently using:
```
    "babel-cli": "^6.9.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "webpack": "^2.2.0"
```

If I was to have a guess, it's likely related to recent changes pulled in to the `package.json` file [here](https://github.com/reduxjs/redux-thunk/commit/82142b8f974fd988761bc7261a6a39cdf1c4bcb5). 

However, that said I thought that webpack 2 used `module` and `jsnext:main` interchangeably. 
Perhaps someone can provide insight on this?

In the meantime, I've locked the dependency to `2.2.0` which has fixed the issue for me in the interim.

I'd be interested to see if others are experiencing similar issues and can create a PR to add back the `jsnext:main` field if necessary.

**Comment by eastwood** [comment]
I setup a small `npm link` and adding back `jsnext:main` doesn't solve the issue. Instead, just pointing to the common js `lib/index.js` seemed to do the job (as it defines `exports.__esModule = true;`).

**Comment by kdschaffe** [comment]
Same issue here, with `"redux-thunk": "^2.2.0"` and `"webpack": "2.1.0-beta.20"`.

`import thunkMiddleware from 'redux-thunk/lib/index';` or locking to 2.2.0 does work for me.

Funny, I had a similar [issue](https://github.com/greensock/GreenSock-JS/issues/269) with gsap last week. Might be time to update Webpack..

**Comment by timdorr** [comment]
I'd consider upgrading Webpack to at least 3.0. The breaking changes in that version are relatively minor compared to 4.0.

**Comment by phistuck** [comment]
@timdorr - not everyone can upgrade Webpack. This is a breaking change... Can you revert this (or create 2.3.1 with the same code as 2.2.0) and update the version to 3.0.0 instead? Most people, I hope, use ^2.0.0 and not * and this way, they will not break anymore.
