### ISSUE TITLE
Getting "TS2315: Type 'Middleware' is not generic."

### ISSUE THREAD

**Issue by tquinlan1992** [reduxjs/redux-thunk#200]
With redux-thunk 2.3.0, awesome-typescript-loader 3.5.0, and typescript 2.8.3 I'm getting the following error.  

Not sure where the cause may lie, if it's a cause from redux-thunk or my setup with typescript.

```
ERROR in [at-loader] ./node_modules/redux-thunk/index.d.ts:14:84
    TS2315: Type 'Middleware' is not generic.
```

I noticed when I upgraded from redux-thunk 2.2.0.  My thunk actions were set up as
```
function callThunkAction(): ThunkAction<void, AppState, void> {
```

and in redux-thunk 2.3.0 I got an error that I need a 4th type argument of type Action.  I changed my code to the following to make the compiler happy.  I'm not sure if my set up of this could be causing the error somehow as well.  Also I'm curious what this 4th type argument provides and example how to use it to your advantage.
```
import { Action } from "redux";

export function fetchProducts(): ThunkAction<void, AppState, void, Action> {
```

**Comment by arieldf** [comment]
@tquinlan1992 I get the exact same error and have not managed to resolve it yet

**Comment by raviqqe** [comment]
Update redux to 4.

**Comment by arieldf** [comment]
@raviqqe I am in fact using Redux 4

**Comment by jonantoine** [comment]
I ran into this as well. My package.json file dependencies look like this:
` "redux": "^3.7.2",`
` "redux-thunk": "^2.2.0",`

I am not ready to update to redux 4.x yet. But the fact that I would have to upgrade to resolve this issue seems to me a breaking change and redux-thunk 2.3.0 should really be 3.0.0.

**Comment by tquinlan1992** [comment]
Thanks!  I should have read the release notes for redux-thunk 2.3.0...
