### ISSUE TITLE
v2.3.0 is giving TS2315: Type 'Middleware' is not generic

### ISSUE THREAD

**Issue by rhtsingh28** [reduxjs/redux-thunk#203]
2.3.0 is giving below error with typescript:
``` TS2315: Type 'Middleware' is not generic. ```

Using 2.2.0 works perfectly.

**Comment by timdorr** [comment]
You need to upgrade to Redux 4.0

**Comment by mattdell** [comment]
If the solution is to upgrade to Redux 4, shouldn't this be a breaking change?

**Comment by mizx** [comment]
Confirming what @mattdell said: For React + Typescript apps, upgrading from 2.2.0 to 2.3.0 is a breaking change.

**For those using Typescript and Redux 3, stick with redux-thunk 2.2.0.**

**Comment by huntinator7** [comment]
Using Typescript 2.9, **Redux 3.7**, Redux-Thunk **2.2.0** and still getting this issue. I'm not able to upgrade to Redux 4.
