### ISSUE TITLE
TS2315: Type 'Middleware' is not generic

### ISSUE THREAD

**Issue by 0x1ad2** [reduxjs/redux-thunk#205]
Yesterday I included `redux-thunk` in my project as middleware and then TypeScript failed. I already read this https://github.com/reduxjs/redux-thunk/issues/203 but I'm running `react-redux: "5.0.7"` and `redux-thunk: "2.3.0"` so updating Redux isn't an option.

```
ERROR in [at-loader] ./node_modules/redux-thunk/index.d.ts:14:84
    TS2315: Type 'Middleware' is not generic.
```

<img width="1899" alt="screen shot 2018-06-22 at 10 40 24" src="https://user-images.githubusercontent.com/1705904/41767393-c51e02a6-7609-11e8-83f7-eeeaa30d502f.png">

**Comment by laat** [comment]
Maybe pin to redux-thunk@2.2.0 ?

**Comment by 0x1ad2** [comment]
@laat trying that as we speak, also trying to downgrade Redux to version `4.x`

**Comment by 0x1ad2** [comment]
Pinning to `redux-thunk@2.2.0` worked, but the bug still has to be fixed.
Redux thunk probably has a mismatch of parameters when calling Middleware from Redux

```
/**
 * A middleware is a higher-order function that composes a dispatch function
 * to return a new dispatch function. It often turns async actions into
 * actions.
 *
 * Middleware is composable using function composition. It is useful for
 * logging actions, performing side effects like routing, or turning an
 * asynchronous API call into a series of synchronous actions.
 */
export interface Middleware {
  <S>(api: MiddlewareAPI<S>): (next: Dispatch<S>) => Dispatch<S>;
}
```

**Comment by timdorr** [comment]
You have to use Redux 4.0 with redux-thunk 2.3.0.

**Comment by scamden** [comment]
is it me or should that be major change? I install a minor update and am forced to make a major update to a core library? seems like this should have been redux-thunk 3.0.0 to me just sayin.

**Comment by MokumJ** [comment]
It doesn't matter which version I use
4.0.0 with 2.3.0,
 5.0.7 with 2.2.0
or the other way around, it keeps on giving this error.
Nobody has a workaround?

**Comment by misstonbon** [comment]
`"redux-thunk": "2.2.0",` change worked for me. I'm on ```"react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "redux": "^3.7.2",```

**Comment by riku179** [comment]
In my case, `redux-localstorage` has blocked version of `redux` in `3.7.0`.
So after I remove `redux-localstorage`, it works fine in `react-redux@5.0.7` and `redux-thunk@2.3.0`.
Check `yarn list|grep redux` and find any packages not using `redux@4.0.0`
