### ISSUE TITLE
Question about a README example

### ISSUE THREAD

**Issue by vibl** [reduxjs/redux-thunk#211]
I don't understand line 226 of the README:
```js
    // We can dispatch both plain object actions and other thunks,
    // which lets us compose the asynchronous actions in a single flow.

==>  return dispatch(
      makeASandwichWithSecretSauce('My Grandma')
```

The whole `makeSandwichesForEverybody`function is a thunk, so it will always be used as an argument to `dispatch`.

So why `return dispatch(` instead of directly returning the value ?

**Comment by timdorr** [comment]
It's so you can access the Promise generated by the thunk. Later on down:

```js
store.dispatch(
  makeSandwichesForEverybody()
).then(() =>
  response.send(ReactDOMServer.renderToString(<MyApp store={store} />))
);
```

**Comment by vibl** [comment]
Sorry but I still don't understand what would be wrong with :
