### ISSUE TITLE
Typing issues with Angular-Redux and Redux 4

### ISSUE THREAD

**Issue by s-uds** [reduxjs/redux-thunk#212]
As previously described in https://github.com/reduxjs/redux-thunk/issues/209
(Angular 6, Redux 4, Angular-Redux/Store 9 and Redux-Thunk 2.3.0)

The following code throws a TS typing error:
```ts
const store = createStore(rootReducer, applyMiddleware(ReduxThunk));
const action = () => {
    return (dispatch, getState) => {
         //Stuff
    }
};

store.dispatch(action); // type error!
```
```red
 error TS2345: Argument of type '(dispatch: any, getState: any) => void' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type '(dispatch: any, getState: any) => void'.
```
The proposed solution removes Redux-Thunk out of the equation by manually enhancing dispatch and that is why I am re-opening the issue.

Thanks a lot,

**Comment by timdorr** [comment]
Your action is just a plain function. You need to type it as a ThunkAction, as TS can't infer that deeply. See our test suite for how to do this: https://github.com/reduxjs/redux-thunk/blob/master/test/typescript.ts#L10
