### ISSUE TITLE
Thunk Action type for Typescript

### ISSUE THREAD

**Issue by anupam-git** [reduxjs/redux-thunk#214]
Hi,

I am using redux-thunk in a typescript project.
But the issue is I am not able to provide correct type for the Thunk Actions Creator along with my other non thunk action creators.

Currently my `dispatch` parameter in `mapDispatchToProps` is typed as follows : 
```javascript

function mapDispatchToProps(dispatch: Dispatch<IActionPayload>, ownProps: any) {
}
```

Need help to properly type dispatch functions.

Thanks.

**Comment by timdorr** [comment]
Check out the TS tests for examples: https://github.com/reduxjs/redux-thunk/blob/master/test/typescript.ts

**Comment by mockdeep** [comment]
Strange that you have to define it using `as ThunkMiddleware`. It seems like because you're exporting the type, that should be given.

**Comment by anupam-git** [comment]
@mockdeep The TS tests given above didn't help much. But after a little digging, I ended up finding the right definition as follows :
```javascript
function mapDispatchToProps(dispatch: ThunkDispatch<IRootState, void, IActionPayload>, ownProps: any) {
}
```

This `ThunkDispatch` accepts a ThunkAction as well as a normal Action.

**Comment by mockdeep** [comment]
@anupam-git sorry, I actually came here based on another error we were seeing. It was complaining about our thunk action creators and a type mismatch between ThunkAction and AnyAction. The only fix that worked for us was using `as ThunkMiddleware` as in the tests.

**Comment by anupam-git** [comment]
Good to know that you have got your solution from this thread.. :)
