### ISSUE TITLE
Missing Next(action)

### ISSUE THREAD

**Issue by vutronic** [reduxjs/redux-thunk#222]
I noticed with redux-thunk, by design, you have to dispatch a new action in the Thunk action method. Is it possible for me to reuse the original action? When the Promise is resolved I want to add some data to my original action and  call next(action) to continue dispatching the same action instance to the reducers. Is this a bad pattern?  You can easily do this with a custom middleware, however, Thunk doesn't pass the 'next' to the action method. Thanks.

**Comment by timdorr** [comment]
`next` isn't available to your thunk, so it's not possible to do that anyways. But in general, we want to encourage a fresh dispatch so it will go through the full middleware chain. Most commonly, that's for logging and ensuring you have good visibility to what's going on in the app.
