### ISSUE TITLE
Are Related-Thunks considered to be best-practice and has real-world examples?

### ISSUE THREAD

**Issue by stavalfi** [reduxjs/redux-thunk#225]
### Related Thunks

The following question is about best practice and finding a real-world example for _related thunks_.

First, let me define _related thunks_:

> Thunks `t_1`,`t_2`,...,`t_n` will be called related thunks if the information returned from `t_i` is a requirement for creating `t_i+1`

### Examples For Related Thunks `thunk1` and `thunk2`

```javascript
const thunk1 = (...params) => (dispatch, getState) => {
  /* do something and return something */
}

const thunk2 = (...params) => (dispatch, getState) => {
  /* do something and return something */
}
```

###### Example 1

```javascript
const compositionOfThunks1 = (...params) => (dispatch, getState) => {
  const thunk1Result = dispatch(thunk1())
  const thunk2Result = dispatch(thunk2(thunk1Result))
  /* do something and maybe return something */
}
```

###### Example 2

```javascript
const compositionOfThunks2 = (...params) => (dispatch, getState) => {
  const promise = dispatch(thunk1()).then(result => dispatch(thunk2(result)))
  /* do something and maybe return something */
}
```

###### Example 1

```javascript
const compositionOfThunks3 = (...params) => (dispatch, getState) => {
  const thunk1Result = dispatch(thunk1(params[0]))
  const thunk2Result = dispatch(thunk2(params[0]))
  /* do something and maybe return something */
}
```

###### Example 2

```javascript
const compositionOfThunks3 = (...params) => (dispatch, getState) => {
  const promise = dispatch(thunk1()).then(resultIsNotUsed => dispatch(thunk2(params[0])))
  /* do something and maybe return something */
}
```

### Questions
1. Are _related thunks_ considered as _redux_/_redux-thunk_ anti-pattern?
2. Is there any real world example that has _related thunks_ in it and can't be solved without them?
3. Same questions for _unrelated-thunks_.

### The purpose of this issue
I'm searching for a variety of opinions from the creators/maintainers of this library about thunks compositions. I want to know if the purpose of composing thunks is to create related or unrelated thunks.

**Comment by timdorr** [comment]
It's certainly a valid pattern if it makes sense for your use case. I don't think it's particularly common, but that doesn't mean you shouldn't use it. Just be careful with it.

**Comment by stavalfi** [comment]
Is there any real world example that has _related thunks_ in it and can't be solved without them?
