### ISSUE TITLE
[TS] cant figure out where should I import `ThunkDispatch` from?

### ISSUE THREAD

**Issue by JustFly1984** [reduxjs/redux-thunk#239]
It seems that only ThunkAction is exported form d.ts. checkd 2.2.0 and 2.3.0

I have this error in VSCode:
```
Module '".../node_modules/redux-thunk/index"' has no exported member 'ThunkDispatch'.ts(2305)
```

**Comment by timdorr** [comment]
It's exported here: https://github.com/reduxjs/redux-thunk/blob/master/index.d.ts#L9

**Comment by JustFly1984** [comment]
Thank you, I had issues with typescript setup
