### ISSUE TITLE
Dispatch typescript signature for conditional dispatch

### ISSUE THREAD

**Issue by butchyyyy** [reduxjs/redux-thunk#242]
**_bug_**

**What is the current behavior?**

Dispatching thunks:

```typescript
dispatch(conditionalThunk)
```

With conditional dispatch

```typescript
const conditionalThunk = () => (dispatch: Dispatch) => {
  if (condition) {
    dispatch(action)
  }
}
```

With Typescript in strict mode will produce following error:

```
Error:(46, 7) TS2345: Argument of type '(dispatch: Dispatch<AnyAction>) => Action<Payload> | undefined' is not assignable to parameter of type 'AnyAction'.
  Property 'type' is missing in type '(dispatch: Dispatch<AnyAction>) => Action<Payload> | undefined' but required in type 'AnyAction'.
```

**What is the expected behavior?**

Proposed solution is to change the Dispatch signature to:

```typescript
export interface Dispatch<A extends Action = AnyAction> {
  <T extends A>(action: T): T | undefined
}

**Comment by timdorr** [comment]
You should use ThunkDispatch from redux-thunk. Check our tests for examples: https://github.com/reduxjs/redux-thunk/blob/master/test/typescript.ts#L123

**Comment by butchyyyy** [comment]
It's what a figured a while ago and was about to close the issue. Thanks a lot for confirming this is the way to go @timdorr !
