### ISSUE TITLE
dispatch not returning inner return value

### ISSUE THREAD

**Issue by albertalquisola** [reduxjs/redux-thunk#244]
im experiencing the same issue on this. Im wondering why this issue was closed without a response?

https://github.com/reduxjs/redux-thunk/issues/190

```
  function testThunk(dispatch, getState) {
    dispatch({ some: 'event' });
    return true;
  }

  const result = dispatch(testThunk);
  console.log(result); // undefined, not true
```

## the documentation explicitly states:
**Any return value from the inner function will be available as the return value of dispatch itself.** This is convenient for orchestrating an asynchronous control flow with thunk action creators dispatching each other and returning Promises to wait for each other’s completion:

https://github.com/reduxjs/redux-thunk#composition

**Comment by markerikson** [comment]
Please provide a CodeSandbox that demonstrates this issue.

Also, review your app to see what other middleware you're using.  If there's another middleware in front of `thunk`, it might not be forwarding the return value onwards.

**Comment by timdorr** [comment]
Yeah, this is likely a misbehaving middleware or just an ordering issue. Not a redux-thunk issue.
