### ISSUE TITLE
Does  thunkMiddleware still exist or  was changed to Reduxthunk ?

### ISSUE THREAD

**Issue by emilnobody** [reduxjs/redux-thunk#256]
Last year  i refactored a react-redux Project with the help of the [redux site](https://redux.js.org/advanced/async-actions).
While creating the [configureStore](https://redux.js.org/recipes/configuring-your-store) i just did like in the Guide/Tutorial/ [Recipe](https://redux.js.org/recipes/configuring-your-store).

I searched the net for the **thunkMiddleware** even for 
  
 "**import thunkMiddleware from 'redux-thunk';**" but nothing poped up 
so , my Question is  "**import thunkMiddleware from 'redux-thunk';**"

deprecated and what is the best practice or the new approch?

Is thunk or Reduxthunk the equivalenz to thunkMiddleware or something total diffrent.?

- [ x] This is not a v0.x issue. 
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior 🤔

connection to the Store 
 an Error Massage that states it  if its deprecated 
## Current Behavior 😯

middleware is not a function  massage in the browser 

## Steps to Reproduce 🕹
The Officel Redux Site 
Link:

1.https://redux.js.org/recipes/configuring-your-store
2.https://redux.js.org/advanced/async-actions

## Context 🔦

 i use the same storestrukture for a new Project and installed all dependencies one by one.
( I did not  copy paste  i redid the Guide ).

The result is that i  got an error middelware is not an function but thats not my propblem 
I just used thunk as middelware and this workte out for me right now 

but i dont know if it is the right approch and bite me in the long run ?

## Your Environment 🌎

| Tech         | Version |
|--------------|---------|
| react-redux  | v7.1.0  |
| React        |   16.8.6      |

**Comment by markerikson** [comment]
Because it's a default export, you can give the import whatever variable name you want.

These are all equivalent:

```js
import thunk from "redux-thunk";
import thunkMiddleware from "redux-thunk";
import reduxThunk from "redux-thunk";
import fred from "redux-thunk";
```
