### ISSUE TITLE
typings downloaded from npm doesn't match the source code

### ISSUE THREAD

**Issue by liqiang372** [reduxjs/redux-thunk#269]
# Bug Report
after I install `redux-thunk` @2.3.0 from npm. Following is the typings I got in node_modules

```
import { Middleware, Action, AnyAction } from "redux";

export interface ThunkDispatch<S, E, A extends Action> {
  <T extends A>(action: T): T;
  <R>(asyncAction: ThunkAction<R, S, E, A>): R;
}

export type ThunkAction<R, S, E, A extends Action> = (
  dispatch: ThunkDispatch<S, E, A>,
  getState: () => S,
  extraArgument: E
) => R;

export type ThunkMiddleware<S = {}, A extends Action = AnyAction, E = undefined> = Middleware<ThunkDispatch<S, E, A>, S, ThunkDispatch<S, E, A>>;

declare const thunk: ThunkMiddleware & {
  withExtraArgument<E>(extraArgument: E): ThunkMiddleware<{}, AnyAction, E>
}

export default thunk;
```

And it misses several typings like `ThunkActionDispatch` and `bindActionCreators` overload from https://github.com/reduxjs/redux-thunk/blob/master/src/index.d.ts

## Package name / version

redux-thunk@2.3.0

## Steps to reproduce
npm install redux-thunk@2.3.0

observe the node_modules/redux-thunk/index.d.ts
## Expected behavior
Should have same typing info as the source code
## Environment

- OS: [e.g., OSX 10.14.6, Windows 10]
- Node/npm version: Node 12.7.0, npm 6.10.0
- Browser: [e.g., Chrome]

**Comment by timdorr** [comment]
They have not been released yet.

**Comment by liqiang372** [comment]
@timdorr is the latest typing going to be released for version 2? And is there any plan for updating the DefinitelyTyped for redux-thunk? It seems the project is not moving forward for quite a long time, let me know if anything we can help
