### ISSUE TITLE
reducer, thunk and  redux devtools

### ISSUE THREAD

**Issue by staminna** [reduxjs/redux-thunk#273]
Apparently createStore() function doesn't allow more than two parameters.
So what I need is the reducer, thunk and chrome redux plugin working at the same time.
I had to use a screenshot because of indentation. 

```
Import React from 'react';
import ReactDOM from 'react-dom';
import {createStore, compose, applyMiddleware} from 'redux';
import {Provider} from 'react-redux';
import reduceCounter from './reducer';
import thunk from 'redux-thunk';

const composeEnhancer = window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__() || compose;

var store = createStore(reduceCounter, composeEnhancer(applyMiddleware(thunk)));
```

<img width="1439" alt="Screenshot 2019-12-15 19 42 26" src="https://user-images.githubusercontent.com/515180/70867973-7d2ca780-1f73-11ea-9683-842aa6cef820.png">

**Comment by markerikson** [comment]
[The "Configuring Your Store" page in the Redux docs](https://redux.js.org/recipes/configuring-your-store) documents how to do this correctly.

Even better, you should use [the `configureStore` function from our official Redux Toolkit package](https://redux-toolkit.js.org/api/configureStore), which automatically sets up thunks and the DevTools extension with no additional work needed on your part.
