### ISSUE TITLE
Publish patch version for TS definitions

### ISSUE THREAD

**Issue by ValentinH** [reduxjs/redux-thunk#275]
# Question

Could you please publish a patch version of the current master? 

Today, I spent 2 hours on a TS issue that was actually already fixed here: https://github.com/reduxjs/redux-thunk/blob/master/src/index.d.ts#L29 😱 

Please 🙏

**Comment by timdorr** [comment]
I'm not yet happy with where the types are, so I don't want to release something broken. 

See #231
