### ISSUE TITLE
withExtraArgument accepting a factory function

### ISSUE THREAD

**Issue by vojtatranta** [reduxjs/redux-thunk#277]
# Feature Request

First, thank you all for making redux and redux-thunk. Everyone who contributed and helped anyhow.

If I may I have any idea how to improve redux thunk.

What if `extraArgument` could be a factory function that receives the same `dispatch, getState`.

Here is an example when it could come handy.

Suppost I have any API class that requires some initial settings. Eg. production vs. staging domains. And some networking interface say `fetch`.

```js
class Api {
   constructor(domain, fetchApi) {
     this.domain = domain
     this.fetchApi = fetchApi
  }
}
```

Right now, I have to create an `Api` instance every time a thunk is called even when the extra argument is used. That is because I needd current state to construct an `Api` instance:
```js
const thunk = (urlToGet) => (dispatch, getState, { fetchApi }) => {
   const api = new Api(getState().config.domain, fetchApi)
   api.get(urlToGet)
  // ...
}
```

However, if I could create an extra argument with both `dispatch` and `getState` I could pass domain or whole getter for domain right into the `Api` instance:
```js
const thunkMiddleware = thunk.withExtraArgument((dispatch, getState) => ({
   api: new Api(getState().config.domain, fetch.bind(window))
})
```
So now in thunk function the code is much simpler and it works much better with composition and handles side effect pretty well and spares code:
```js
const thunk = (urlToGet) => (dispatch, getState, { api }) => {
   api.get(urlToGet)
  // ...
}
```

I guess this is a small change yet it can yield great improvement and simplify a lot of code. It supports testability, modularity, and reusability.

What do you think?

**Comment by timdorr** [comment]
We've been over this a bunch before: #232 #113 #85

Short answer: It ain't happening.

**Comment by vojtatranta** [comment]
Oh, OK. I did not find it.

Thank you for your response. Will make a separate Middleware.
