### ISSUE TITLE
typescript types seem off for ThunkAction/ThunkDispatch

### ISSUE THREAD

**Issue by ORESoftware** [reduxjs/redux-thunk#280]
The ThunkAction should return a function that takes dispatch (a known type of ThunkDispatch) as it's first argument:

![Screenshot from 2020-03-03 11-30-40](https://user-images.githubusercontent.com/11139560/75812161-978c4b00-5d42-11ea-80de-8f34e2721421.png)

the problem here is that dispatch() does not return a promise according to the types, but it should/does.

**Comment by laat** [comment]
This should work:
```ts
import { Action } from "redux";
import { ThunkAction } from "redux-thunk";
const logout: ThunkAction<any, any, any, Action> = dispatch => {
  dispatch(() => Promise.resolve()).then();
};
```

Also, look at the comments here https://github.com/reduxjs/redux-thunk/issues/213

[Redux Toolkit "Advanced Tutorial" docs page](https://redux-toolkit.js.org/tutorials/advanced-tutorial) shows a recommended approach to working with thunks in TS

**Comment by laat** [comment]
The [Redux docs "Usage with TypeScript"](https://redux.js.org/recipes/usage-with-typescript/#usage-with-redux-thunk) documents this
