### ISSUE TITLE
Check for name & arguments of a redux-thunk action in middleware

### ISSUE THREAD

**Issue by felire** [reduxjs/redux-thunk#282]
Hi, I wanna know if there is a possibility to check for the arguments of a redux-thunk action. For example in your middleware you do somethink like type of action === 'function'. 
I would like to check something like action.name and action.arguments is it possible?

**Comment by markerikson** [comment]
I'm not sure what you're actually trying to accomplish here.  Can you give an example?

**Comment by felire** [comment]
I have actions like this one: 

```
updateCart: (data, action, options = {}, cartIndex) => async (dispatch, getState) => {
    const {
....
....
....
```

I would like to create my own middleware and when the action are functions/thunk actions check for the name of the function and for the arguments that were passed to the function when it was dispatched.
For example, if someone dispatch updateCart doing this:
`
dispatch(actions.updateCart(data1, data2, data3, data4))
`
In my middleware I would like to check for the name and for the arguments and do something, for example:

```
actions = ['updateCart', ...]
if(actions.includes(action.name)){
     save(action.argument). --> In this step I want to access to data1, data2, etc
}
```

**Comment by markerikson** [comment]
No, you can't access values that are _inside_ a closure from _outside_ the closure.  That's impossible in JS.
