### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by mikecann** [reduxjs/redux-thunk#284]
Apologies if this has already been asked, I couldnt find it in the issues or via google however.

# Question

Is it possible to log thunks? Im thinking something like `Thunk X has started`, `Thunk X has resolved`, `Thunk X has failed` sort of thing..

**Comment by markerikson** [comment]
Not in that sense, no.  A thunk is just a function, and so it has no inherent lifecycle.  [A thunk can have any sync or async logic inside](https://gist.github.com/markerikson/ea4d0a6ce56ee479fe8b356e099f857e).  However, any actual actions dispatched will show up in the Redux DevTools, no matter where you dispatch them from.
