### ISSUE TITLE
Can we release the current master?

### ISSUE THREAD

**Issue by swernerx** [reduxjs/redux-thunk#286]
There were a few major fixes to the TS definitions which were never released. 2.3.0 was released in 2018. A lot of fixes were made in 2019 but never released. Any chance to make this possible?

**Comment by timdorr** [comment]
They are still not acceptable to me. I'm waiting to release Redux 5 in TypeScript and then we can examine this library, as that will have further changes here.

**Comment by delanni** [comment]
Maybe it's not acceptable for you but the `package.json` on the latest released version (2.3.0) still doesn't list `redux` as a peer dependency. This, with more modern package managers, like PNPM, causes a major issue. Namely, the type definitions released with `redux-thunk` are importing types from `redux`, but the dependency will not be present, thus the type resolver will fail to figure out what that is. 

I'd hate to have to go and create a DefinitelyTyped entry to bridge over this shortcoming, but this is nothing I can fix in post, the currently released version is just incorrect, but the current master seems to be fine.
