### ISSUE TITLE
Udemy tutorial for redux thunk

### ISSUE THREAD

**Issue by E-RROR** [reduxjs/redux-thunk#290]
Hi, im Sina.
im instructor on udemy and recently i created a course with name "Learn redux thunk".
actually now it is in progress for review
https://www.udemy.com/course/draft/3194916/?instructorPreviewMode=guest
its the link.
Can i put the link in the thunk docs?

**Comment by markerikson** [comment]
I can't say I understand why an actual _course_ would be needed for thunks :)  Appreciate the thought, but don't see a need to add this atm.
