### ISSUE TITLE
Typescript type for `ThunkAction` doesn't limit `dispatch` arguments

### ISSUE THREAD

**Issue by Ryunaq** [reduxjs/redux-thunk#298]
# Bug Report

## Package name / version

redux-thunk@2.3.0

## Description
Typescript definition for `ThunkAction` allows for additional properties inside the dispatch call. For some reason, only the properties of the type of the action are guaranteed, but you can add more.

## Steps to reproduce
```ts
import { ThunkAction } from 'redux-thunk';

const GET_INFO = 'GET_INFO';

interface GetInfo {
  type: typeof GET_INFO;
  payload: string;
}

export const thunkSendMessage = (): ThunkAction<
  void,
  any,
  unknown,
  GetInfo
> => async (dispatch) => {
  dispatch({
    type: GET_INFO,
    payload: 'Got Info',
    wrongProperty: 'blahblah',
  });
};
```

## Expected behavior
Some typescript warning on `wrongProperty: 'blahblah',`. I don't think this is intentional.

## Environment

- Typescript version: 4.02
- Node version: Node 12.16.1

**Comment by markerikson** [comment]
This sounds like perfectly normal JS behavior to me.  TS has always allowed passing types with extra fields as far as I know, because the type fulfills the core contract - ie, `{a, b, c}` matches expectation of `{a, c}`.

**Comment by Ryunaq** [comment]
Just picked up TS so I may be wrong but it seems to me that according to the [handbook](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks) excess property checks are enabled for object literals. That why the following generates a warning in my environment (assuming I'm in the same file as in my previous example):

```ts
let myAction: GetInfo = {
    type: GET_INFO,
    payload: 'Got Info',
    wrongProperty: 'blahblah', // <-- get warning
}
```
```
Type '{ type: "GET_INFO"; payload: string; wrongProperty: string; }' is not assignable to type 'GetInfo'.
  Object literal may only specify known properties, and 'wrongProperty' does not exist in type 'GetInfo'.
```

So (non-thunk) action creators do follow my expected behavior which gives some evidence that TS is with me on this one.

I think this fails `ThunkDispatch` because in its definition the return type extends the original one (`TAction extends TBasicAction` on line 30). I would argue that my expected behavior would be the correct one, because if I can dispatch anything it would be kind of meaningless to define my interface for my action. I tried to solve this but as I said kind of new on this and there is so much overloading that I didn't know what to do.
