### ISSUE TITLE
Property 'then' does not exist on type (dispatch) => Promise<unknown> ; while returning a Promise in action-creator

### ISSUE THREAD

**Issue by gauravkrp** [reduxjs/redux-thunk#307]
In my Redux actions creator, I am returning a Promise which has to resolve/reject depending upon the success/failure of async api call.

I'm using next.js with typescript.
Code is working fine but typescript implementation is showing error - ````Property 'then' does not exist on type '(dispatch: any)```` 

Codesandbox demo - https://codesandbox.io/s/hungry-clarke-1p1m4?file=/pages/index.tsx

````
/* component file */

const Index = (props: any) => {
  const [isFetching, setFetched] = useState(false);
  const getDataFromStore = useSelector((state: any) => state.todos);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(actions.fetchData())
      .then((response: any) => {
        console.log(`fetched data`, response);
        setFetched(false);
      })
      .catch((err: any) => console.log(err));
    console.log("data-", getDataFromStore);
  }, [isFetching]);

// rest of the codes follow here.


/*  actions.tsx */

// fetch data from server
export const fetchData = () => (dispatch: any, getState: any) => {
  console.log(`action created, fetching data`);
  return new Promise((resolve, reject) => {
    axios
      .get(API_PATH)
      .then((response: any) => {
        console.log(response);
        resolve(response);
        dispatch(FETCH_DATA(response.data));
        dispatch(API_SUCCESS("DONE"));
      })
      .catch(async (err: any) => {
        reject("error");
      });
  });
};

````

Please go to pags/index.tsx and see line no 13. on pages/index.tsx You will notice a type error - ````Property 'then' does not exist on type '(dispatch: any)````

[![enter image description here][1]][1]

How to resolve this types bug?

  [1]: https://i.stack.imgur.com/iPBR4.png

**Comment by markerikson** [comment]
Closed due to cross-posting across repos.
