### ISSUE TITLE
Why not next?

### ISSUE THREAD

**Issue by enahsor** [reduxjs/redux-thunk#313]
# Question

I've been playing around with Redux and Redux-Thunk and I'm curious as to why thunk doesn't call the next function when an action is of the type function?
Wouldn't this behavior make it difficult for thunk to work with other middlewares since the puck basically stops at thunk?

Am I missing something? If yes, help me understand.

**Comment by markerikson** [comment]
The store throws an error when anything that is not a valid action object is passed to the core `store.dispatch` method.

Functions are not valid action objects.  Therefore, they must _not_ be allowed to reach the reducers.

Middleware are allowed (and encouraged!) to intercept non-plain-action-object values, do some logic, and then dispatch real action objects.  For example, the [`redux-promise` middleware](https://github.com/redux-utilities/redux-promise) lets you pass a promise directly to `dispatch` (or as part of `action.payload`), intercepts that promise, and then dispatches actions based on the promise's resolution.

Similarly, the thunk middleware intercepts functions passed to dispatch, calls them, and allows you to dispatch further actions.
