### ISSUE TITLE
import  'redux-thunk/extend-redux' doesn't work

### ISSUE THREAD

**Issue by ZeJ0hn** [reduxjs/redux-thunk#329]
# Question

Hi, I use a react app with redux and redux-thunk. We move the app from JS to Typescript.
I found in the source code of extend-redux.d.ts that I need to import the file to have the support of`bindActionCreators` with Typescript.
```
/**
 * Globally alter the Redux `bindActionCreators` and `Dispatch` types to assume
 * that the thunk middleware always exists, for ease of use.
 * This is kept as a separate file that may be optionally imported, to
 * avoid polluting the default types in case the thunk middleware is _not_
 * actually being used.
 *
 * To add these types to your app:
 * import 'redux-thunk/extend-redux'
 */
```

So I tried to add the import but when I start the app with `npm start`, I got this error:
```
Failed to compile.

./src/store/index.tsx
Module not found: Can't resolve 'redux-thunk/extend-redux' in ...
```

I cannot find how import this module.
Can you help me?

Thank you

**Comment by timdorr** [comment]
You need to have at least version 2.4.0 installed. But this definitely works, as [we do this on our own test suite](https://github.com/reduxjs/redux-thunk/blob/master/typescript_test/typescript_extended/extended-redux.ts#L22).

**Comment by timdorr** [comment]
I'm not sure, as the file definitely exists in that version: https://unpkg.com/browse/redux-thunk@2.4.1/

**Comment by markerikson** [comment]
As usual, we'd need to see a repro of the issue to better understand why this might not be working.

**Comment by ZeJ0hn** [comment]
Hi,

I tried to add this in the package.json.
```
  "exports": {
    "./extend-redux": "./extend-redux.d.ts"
  }
```
It seems to work but I have another issue during the npm start:
```
Module parse failed: Unexpected token (13:8)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|  * import 'redux-thunk/extend-redux'
|  */
> declare module 'redux' {
```

**Comment by timdorr** [comment]
Yeah, that's just tricking the webpack loader stack to use the built-in loader, which isn't Typescript-aware. 

Does `import type 'redux-thunk/extend-redux'` work?

**Comment by ZeJ0hn** [comment]
Unfortunatelly, it doesn't help :-(

**Comment by markerikson** [comment]
@ZeJ0hn in that case could you put together a sandbox or project that shows the error happening?

**Comment by ZeJ0hn** [comment]
@markerikson you have an example here [https://github.com/ZeJ0hn/redux-thunk-issue](https://github.com/ZeJ0hn/redux-thunk-issue)

I just followed my previous instructions :-)

**Comment by timdorr** [comment]
Ah, it's Webpack's fault, as it's getting to the loader before tsc does. Not really a redux-thunk issue, just with the build tooling.

You can work around it with a (triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html). Just add this at the top of your file or in react-app-env.d.ts
```ts
/// <reference types="redux-thunk/extend-redux" />
```

**Comment by ZeJ0hn** [comment]
Thank you for your help!
