### ISSUE TITLE
When running server getting expected errors

### ISSUE THREAD

**Issue by karol-oman** [reduxjs/redux-thunk#332]
# Bug Report

## Package name / version

redux-thunk@2.3.0

## Description

I am running my server through docker and then getting this error

## Environment

- OS: [Mac OS Monterey]
- Node/npm version: [e.g., Node 12/npm 8.5.5]
- Browser: [Chrome]

## Additional context / screenshots
Getting this issue when I run my server:
`ERROR in node_modules/pdfjs-dist/types/src/display/api.d.ts(1431,5): error TS1127: Invalid character.`
`web-app_1  | node_modules/pdfjs-dist/types/src/display/metadata.d.ts(10,5): error TS1127: Invalid character.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(1,13): error TS1005: '=' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(1,40): error TS1005: ';' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(2,13): error TS1005: '=' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(2,38): error TS1005: ';' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(3,1): error TS1128: Declaration or statement expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(3,13): error TS1005: ';' expected.`
`web-app_1  | node_modules/redux-thunk/es/index.d.ts(3,87): error TS1005: ';' expected.`

**Comment by markerikson** [comment]
This doesn't appear to have anything to do with redux-thunk.  It seems like you have some kind of build setup that is trying to (wrongly) parse TS declaration files as if they were actual source code.

**Comment by karol-oman** [comment]
> This doesn't appear to have anything to do with redux-thunk. It seems like you have some kind of build setup that is trying to (wrongly) parse TS declaration files as if they were actual source code.

How can it be an TS issue when it's JS files?
