### ISSUE TITLE
Current implemention doesn't allow Jest or any other mock tool to spy on dispatch or getState

### ISSUE THREAD

**Issue by danyg** [reduxjs/redux-thunk#335]
# Bug Report

The current implementation doesn't allow spying or mock `store.dispatch` or `store.getState`
as currently, the definition of createThunkMiddleware dereference store. dispatch and getState keep the value of creation time, when the store is created, preventing in architectures when the store is built on import time (singleton) to spy or mock the response of these two methods on the store.

The solution would be to not dereference it so that every time a thunk is invoked the current implementation of these two methods is used.

A [PR](https://github.com/reduxjs/redux-thunk/pull/336) is provided with tests for the solution.

## Package name / version

redux-thunk@2.4.1

## Description

- Create a store with a thunk which dispatches an action
- use `jest.spyOn(store, 'dispatch')` or similar tooling like sinon
- expect the dispatch to have been called with the dispatched action
- Fails to find such action as the `dispatch` invoked by the thunk is the original dispatch (store dispatch) and not the monkey patched one by jest

## Expected behaviour

- Create a store with a thunk which dispatches an action
- in test environment use `jest.spyOn(store, 'dispatch')` or similar tooling like sinon
- expect the dispatch to have been called with the dispatched action
- EXPECTED: the assertion to pass as thunk uses the monkey-patched implementation of dispatch.

## Environment

- OS: OSX 12.2.1
- Node/npm version: [e.g., Node 16.18.0/npm 8.19.2]
- Browser: N/A

### Generated code store reference at store creation time
<img width="692" alt="image" src="https://user-images.githubusercontent.com/1834409/200366242-0aa21c8a-573e-4764-a8fc-f3f1a591ff4a.png">

**Comment by phryneas** [comment]
For what it's worth, we usually don't want to encourage mocking like this *too much*. It is oven overused and gives very little actual confidence to test these little units instead of testing actual store interactions with all the moving parts included.

If you want to do something like this, you could create a store enhancer to enable that behavior for your code base, but I'm not too much in favor of adding more code on our side to enable a feature that we actually want to discourage.

An example enhancer could look like this:

```ts
import { configureStore } from "@reduxjs/toolkit";
import { Store, StoreEnhancer } from "redux";

const mockableEnhancer: StoreEnhancer<
  {
    mockable: Pick<Store, "dispatch" | "getState">;
  },
  {}
> = (next) => (...args): any => {
  const store = next(...args);
  const mockable = {
    dispatch: store.dispatch,
    getState: store.getState
  };
  return Object.assign({}, store, {
    mockable,
    getState() {
      return mockable.getState();
    },
    dispatch(action: any) {
      return mockable.dispatch(action);
    }
  });
};

const store = configureStore({
  reducer: () => 0,
  enhancers: (e) => e.concat(mockableEnhancer)
});

// now we mock
store.mockable.getState = () => "foo";

// and thunks access the mock
store.dispatch((dispatch, getState) => {
  console.log(getState());
});
```

**Comment by danyg** [comment]
@phryneas I'm in agreement with you, I think the best idea would be to have a store that is not a singleton and only load the slices of it that are required in your tests.
But legacy code sometimes requires getting worst before getting better.

The test is hard, and forcing it to test in a way that people and architectures are not prepared to, do could cause discourage people to test at all, or simply tag tests as impossible.

Also, I think there is a very valid scenario where you want to keep your test slim, fast and quick to write, by testing Components Integrated with the store for a happy path and a sad path, but other scenarios can just be covered with a contract test, which this PR helps to achieve.
Also, scenarios where you create a common (internal) component library where part of the API is that your components dispatch actions to be handled in consumers' apps. In the current status will force you to write TestDoubles when a simple could solve the issue.
I think limiting the kind of tests that you prefer to discourage can prevent other kinds of architectures that you are not thinking about right now, which are totally valid and could benefit from this change, and also transition states in big and legacy projects.

The enhancer you propose will require adding a Test code to production code, as the store is exactly the same as it is for production, and adding this enhancer only on test via an env prop could be even worst than my proposed solution.

In my opinion, it's always better to allow to test in any way possible, than force people to test in your opinionated way (which I agree with). Encourage them to test better but never force nor limit.

I think in the industry we suffer too much elitism as regard testing and how is supposed to be tested, or TDD is king and we are creating a toxic environment for those that are outside of the "good practices" (personally follow TDD, and Kent Beck's ideas)

Just as a last argument, if I mock `store.getState` or `store.dispatch`, I expect to be mocked I don't expect to be cached by a library.

I truly hope you change your mind about this. I know it can be annoying to accept a PR like this from your point of view, but because there are bad cases to use, are also valid and helpful ones.

Cheers!
