### ISSUE TITLE
Warning in React-thunk while installing

### ISSUE THREAD

**Issue by McGwery** [reduxjs/redux-thunk#354]
# Warning
What is this cause in react-native **Expo App SDK 49** how to resolve this warning  
_warning " > react-thunk@1.0.0" has incorrect peer dependency "react@~0.14.0 || ^15.0.0"._
I'm using **react:18.2.0** and **react-native:0.72.6**

**Comment by markerikson** [comment]
I think there's multiple problems there:

- This package is `redux-thunk`, not `react-thunk`
- The current version is `2.4.2`, not `1.0.0`
- `redux-thunk` has nothing to do with React :)
