### ISSUE TITLE
Query About Redux Thunk

### ISSUE THREAD

**Issue by EhsanKey** [reduxjs/redux-thunk#355]
# Question

I have a question regarding Redux Thunk, and I'd appreciate some clarification on it. The code provided below demonstrates an asynchronous data fetching approach in Redux, using Axios, without the use of Redux Thunk. 

```javascript
import { useDispatch } from 'react-redux';
import axios from 'axios';

export const fetchItems = async (dispatch) => {
  try {
    const response = await axios.get('https://fortnite-api.theapinetwork.com/upcoming/get');
    const items = response.data;

    dispatch({ type: 'FETCH_ITEMS_SUCCESS', payload: items.data });
  } catch (error) {
    dispatch({ type: 'FETCH_ITEMS_FAILURE', error: error.message });
  }
}

// components/App.js

import React from 'react';
import { useDispatch } from 'react-redux';
import { fetchItems } from './api';

const App = () => {
  const dispatch = useDispatch();

  const handleClick = () => {
    fetchItems(dispatch);
  }

  return (
    <div>
      <button onClick={handleClick}>Fetch Items</button>
    </div>
  );
}

export default App;
```

My query revolves around the necessity of using Redux Thunk in this context and the benefits it offers. I would appreciate any insights or explanations on why Redux Thunk is a preferred approach for handling asynchronous actions in Redux.

Thank you for your guidance.

**Comment by markerikson** [comment]
This is covered in our tutorials and docs:

- https://redux.js.org/tutorials/fundamentals/part-6-async-logic
- https://redux.js.org/tutorials/essentials/part-5-async-logic
- https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics
- https://redux.js.org/usage/side-effects-approaches
