### ISSUE TITLE
`thunk` as a named export?

### ISSUE THREAD

**Issue by fiznool** [reduxjs/redux-thunk#359]
# Question

The [release notes for v3.1.0](https://github.com/reduxjs/redux-thunk/releases/tag/v3.1.0) mention that if using the manual setup (i.e. without RTK), the `thunk` middleware should be imported using a named import, i.e. `import { thunk } from 'redux-thunk';`. However, the current `README` [demonstrates a default export](https://github.com/reduxjs/redux-thunk/blob/3eea8af58dfaede8139564fad61570df4cbb604d/README.md#manual-setup), i.e. `import thunk from 'redux-thunk';`

Could you clarify whether the README is still up to date, or whether this needs to be changed?

**Comment by EskiMojo14** [comment]
the README needs an update, good spot - the release notes are correct.

**Comment by fiznool** [comment]
Submitted a PR with my understanding of the changes needed.

**Comment by timdorr** [comment]
@fiznool That PR is in the wrong repo. It needs to be submitted here.
