### ISSUE TITLE
export compatible with CommonJS proposal

### ISSUE THREAD

**Issue by fibo** [reduxjs/redux-thunk#72]
Hi,

first of all, thanks for your amazing work, you are helping a lot of people to develop the right way.

May I propose to use this kind of export [here](https://github.com/gaearon/redux-thunk/blob/master/src/index.js#L14)

``` javascript
export default module.exports = thunk;
```

**Comment by timdorr** [comment]
I'll be switching us to Rollup and will provide a CJS export.
