### ISSUE TITLE
Proposal: parallel utility function

### ISSUE THREAD

**Issue by SirCmpwn** [reduxjs/redux-thunk#99]
I was going to make this as a pull request, but I don't grok all the typescript stuff going on here (and testing it the way I wanted would have involved adding sinon).

Something to this effect:

``` js
export function parallel(thunks) {
  return async (dispatch, getState) =>
    await Promise.all(thunks.map(t => t(dispatch, getState)));
}
```

Used like so:

``` js
const [ aresult, bresult, cresult ] =
  await dispatch(parallel(athunk(), bthunk(), cthunk()));
```

**Comment by otakustay** [comment]
I don't think adding utility flow control functions to redux-thunk is a good idea, this time we add `parallel` and next time we will add `series`, `throttle`, `debounce` and so on...

In other words, parallel is the easiest to handle, just call `dispatch` multiple times:

```js
let [aResult, bResult, cResult] = await Promsie.all([dispatch(athunk), dispatch(bthunk), dispatch(cthunk)]);
```

I don't quite get the benefit of having an extra `parallel` utility function, even if you really want a `parallel` utility, it should be much simpler than you expected:

```js
let parallels = ...thunks => Promise.all(thunks.map(dispatch));
let [a, b, c] = parallels(thunkA, thunkB, thunkC);
```

This does not involve redux-thunk's internal implement at all

**Comment by SirCmpwn** [comment]
>even if you really want a parallel utility, it should be much simpler than you expected:

This whole library is 14 lines, 12 if you remove extra line breaks. With this line of reasoning you could delete the repo and tell people to implement it themselves.

**Comment by SirCmpwn** [comment]
>this time we add parallel and next time we will add series, throttle, debounce and so on...

Valid point

**Comment by otakustay** [comment]
npm ecosystem encourages small and dedicated packages, if 2 things are not coupled to each other's internal implement, they'd better be different package, in this way a `redux-thunk-flow` package could help more users

Another point is that in my mind it is not a good practice to `await` a `dispatch`, in a full fledged multi-layered app, redux-thunk is an dependency injection tool to provide dispatching ability to a certain layer, and this layer should be focused on "invoking business logic and do dispatching stuff", the core business logic should spread in another layer, so `await` is better to used with the business logic layer but not the thunk itself
